### ISSUE TITLE
RemoveUnusedLocalFiles doesn't always pass on first go

### ISSUE THREAD

**Issue by MRose90** [semdiffdotnet/semdiff#58]
Need to figure out if this is a bug in the test or a bug with the actual code. Sometimes the test fails even if the file is deleted.

**Comment by haroldhues** [comment]
After poking around there are two possible issues
 * Windows doesn't delete files immediately http://stackoverflow.com/a/25421332/2899390
 * EtagNoChanges needs to be null so that it doesn't get short circuited before the update

In my testing it seemed like it was the second one, but I have my doubts
